spring:
  application:
    name: api-gateway

server:
  port: 7999

zuul:
  prefix: /api
  routes:
    user:
      path: /user/**
      serviceId: user-service

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
