server:
  port: 8062
spring:
  datasource:
    url: jdbc:mysql://${RESMAN_SERVICE_ADDR:master.qyos.com:30799}/cybertron_resman?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 1q2w3e4r
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 15
      idle-timeout: 30000
      auto-commit: true
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  jpa:
    generate-ddl: true
  cloud:
    config:
      discovery:
        enabled: true
        service-id: configsr

bigbang:
  url: api-gateway-qybe.qyos.com
openshift:
  url: https://master.qyos.com:8443
  username: admin
  password: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
